//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Course
    {
        public Course()
        {
            this.Session = new HashSet<Session>();
            this.TeacherCourse = new HashSet<TeacherCourse>();
            this.StudentCourse = new HashSet<StudentCourse>();
        }

        [Required]
        [StringLength(50)]
        [Display(Name = "Course Id")]
        public string Course_Id { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "Course Name")]
        [RegularExpression("^[a-zA-Z\\s]+$", ErrorMessage = "Course Name is not in correct Formate")]
        public string Course_Name { get; set; }

        [Required]
        [Display(Name = "Credit Hours")]
        public int Credit_Hours { get; set; }

        [Required]
        [Display(Name = "Semester Id")]
        public int Semester_Id { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Degree Id")]
        public string Degree_Id { get; set; }
    
        public virtual ICollection<Session> Session { get; set; }
        public virtual ICollection<TeacherCourse> TeacherCourse { get; set; }
        public virtual ICollection<StudentCourse> StudentCourse { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual Degree Degree { get; set; }
    }
}
