//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Degree
    {
        public Degree()
        {
            this.Semester = new HashSet<Semester>();
            this.Course = new HashSet<Course>();
            this.Student = new HashSet<Student>();
        }

        [Required]
        [StringLength(50)]
        [Display(Name = "Degree Id")]
        public string Degree_Id { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "Degree Name")]
        [RegularExpression("^[a-zA-Z\\s]+$", ErrorMessage = "Degree Name is not in correct Formate")]
        public string Degree_Name { get; set; }


        [Required]
        [StringLength(50)]
        [Display(Name = "Dept Id")]
        public string Dept_Id { get; set; }
    
        public virtual ICollection<Semester> Semester { get; set; }
        public virtual ICollection<Course> Course { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<Student> Student { get; set; }
    }
}
