//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Department
    {
        public Department()
        {
            this.Teacher = new HashSet<Teacher>();
            this.Degree = new HashSet<Degree>();
        }

        [Required]
        [StringLength(50)]
        [Display(Name = "Dept Id")]
        public string Dept_Id { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "Dept Name")]
        [RegularExpression("^[a-zA-Z\\s]+$", ErrorMessage = "Name is not in correct Formate")]
        public string Dept_Name { get; set; }
    
        public virtual ICollection<Teacher> Teacher { get; set; }
        public virtual ICollection<Degree> Degree { get; set; }
    }
}
