//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Semester
    {
        public Semester()
        {
            this.Student = new HashSet<Student>();
            this.Course = new HashSet<Course>();
        }

        [Display(Name = "Semester Id")]
        public int Semester_Id { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Degree Id")]
        public string Degree_Id { get; set; }

        [Required]
        [Display(Name = "Semester Name")]
        public string Semester_Name { get; set; }
    
        public virtual Degree Degree { get; set; }
        public virtual ICollection<Student> Student { get; set; }
        public virtual ICollection<Course> Course { get; set; }
    }
}
