//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class SessionTime
    {
        public SessionTime()
        {
            this.Session = new HashSet<Session>();
        }

        [Display(Name = "SessionTime Id")]
        public int SessionTime_Id { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Session Time")]
        public string Session_Time { get; set; }
    
        public virtual ICollection<Session> Session { get; set; }
    }
}
