//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Session
    {
        public Session()
        {
            this.Attendance = new HashSet<Attendance>();
        }

        [Display(Name = "Session Id")]
        public int Session_Id { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Course Id")]
        public string Course_Id { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Teacher Id")]
        public string Teacher_Id { get; set; }

        [Required]
        [Display(Name = "Date")]
        public System.DateTime Date { get; set; }

        [Required]
        [Display(Name = "SessionTime Id")]
        public int SessionTime_Id { get; set; }

        public Nullable<int> Total_Session { get; set; }
    
        public virtual ICollection<Attendance> Attendance { get; set; }
        public virtual Course Course { get; set; }
        public virtual SessionTime SessionTime { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
