//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class StudentCourse
    {
        [Display(Name = "StudentCousre Id")]
        public int StudentCourse_Id { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Student Id")]
        public string Student_Id { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Course Id")]
        public string Course_Id { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Course Course { get; set; }
    }
}
