//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Student
    {
        public Student()
        {
            this.Attendance = new HashSet<Attendance>();
            this.StudentCourse = new HashSet<StudentCourse>();
            this.TeacherCourseStudent = new HashSet<TeacherCourseStudent>();
            this.StudentCreditHours = new HashSet<StudentCreditHours>();
        }

        [Required]
        [StringLength(50)]
        [Display(Name = "Student Id")]
        public string Student_Id { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [StringLength(200, MinimumLength = 3, ErrorMessage = "The field Password must be a string with a minimum length of 4 and a maximum length of 50.")]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Required]
        [StringLength(100)]
        [RegularExpression("^[a-zA-Z\\s]+$", ErrorMessage = "First Name is not in correct Formate")]
        [Display(Name = "First Name")]
        public string Name { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "Last Name")]
        [RegularExpression("^[a-zA-Z\\s]+$", ErrorMessage = "Last Name is not in correct Formate")]
        public string Sur_Name { get; set; }

        [Required]
        [StringLength(100)]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email")]
        public string email { get; set; }

        [Required]
        [Display(Name = "Badge#")]
        public int Badge_No { get; set; }

        [Required]
        [Display(Name = "Semester")]
        public int Semester_Id { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Degree Id")]
        public string Degree_Id { get; set; }

        public string Password_Salt { get; set; }

        public virtual ICollection<Attendance> Attendance { get; set; }
        public virtual ICollection<StudentCourse> StudentCourse { get; set; }
        public virtual ICollection<TeacherCourseStudent> TeacherCourseStudent { get; set; }
        public virtual ICollection<StudentCreditHours> StudentCreditHours { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual Degree Degree { get; set; }
    }
}
