//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TeacherCreditHours
    {
        [Display(Name = "StudentCreditHours Id")]
        public int TeacherCreditHours_Id { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Teacher Id")]
        public string Teacher_Id { get; set; }

        [Required]
        [Display(Name = "Credit Hours")]
        public int CreditHours { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
