//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.Session = new HashSet<Session>();
            this.TeacherCreditHours = new HashSet<TeacherCreditHours>();
        }

        [Required]
        [StringLength(50)]
        [Display(Name = "Teacher Id")]
        public string Teacher_Id { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [StringLength(200, MinimumLength = 3, ErrorMessage = "The field Password must be a string with a minimum length of 4 and a maximum length of 50.")]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "First Name")]
        [RegularExpression("^[a-zA-Z\\s]+$", ErrorMessage = "First Name is not in correct Formate")]
        public string Name { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "Last Name")]
        [RegularExpression("^[a-zA-Z\\s]+$", ErrorMessage = "Last Name is not in correct Formate")]
        public string Sur_Name { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "Designation")]
        [RegularExpression("^[a-zA-Z\\s]+$", ErrorMessage = "Designation is not in correct Formate")]
        public string Designation { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Dept Id")]
        public string Dept_Id { get; set; }

        public string Password_Salt { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<Session> Session { get; set; }
        public virtual ICollection<TeacherCreditHours> TeacherCreditHours { get; set; }
    }
}
